// src/book_gen.rs
use crate::models::post::Post;
use anyhow::Result;
use mdbook::MDBook;
use rbatis::RBatis;
use std::fs;
use std::path::Path;

// 定义 mdbook 的工作目录
const BOOK_ROOT: &str = "data/book_workspace";

pub async fn rebuild_book(rb: &RBatis) -> Result<()> {
    println!("🔄 Starting mdBook build process...");

    // 1. 准备目录结构
    // data/book_workspace/
    // ├── book.toml
    // └── src/
    //     ├── SUMMARY.md
    //     └── ...posts...
    let src_dir = Path::new(BOOK_ROOT).join("src");
    if src_dir.exists() {
        fs::remove_dir_all(&src_dir)?;
    }
    fs::create_dir_all(&src_dir)?;

    // 2. 获取所有文章 (按时间倒序)
    // 注意：这里需要你确保 models/post.rs 里有按时间排序的查询，或者直接 select_all 拿到内存排
    let mut posts = Post::select_all(rb).await.unwrap_or_default();
    // 简单按 ID 倒序（假设 ID 自增）
    posts.sort_by(|a, b| b.id.cmp(&a.id));

    // 3. 生成 SUMMARY.md (左侧导航栏)
    let mut summary_content =
        String::from("# Summary\n\n[Introduction](README.md)\n\n# Blog Posts\n");

    // 4. 生成 README.md (首页)
    let readme_content = format!(
        "# Welcome to My Rust CMS\n\nCurrently there are {} posts generated by mdBook.",
        posts.len()
    );
    fs::write(src_dir.join("README.md"), readme_content)?;

    // 5. 遍历文章，生成 Markdown 文件并写入 SUMMARY
    for post in posts {
        let file_name = format!("{}.md", post.slug);
        let file_path = src_dir.join(&file_name);

        // 写入文章内容
        // 可以在这里加个标题头
        let content_with_title = format!("# {}\n\n{}", post.title, post.content);
        fs::write(file_path, content_with_title)?;

        // 添加到目录
        // 格式: - [Title](filename.md)
        summary_content.push_str(&format!("- [{}]({})\n", post.title, file_name));
    }

    // 6. 写入 SUMMARY.md
    fs::write(src_dir.join("SUMMARY.md"), summary_content)?;

    // 7. 生成 book.toml (配置文件)
    let config_content = r#"
[book]
authors = ["Rust CMS"]
language = "en"
multilingual = false
src = "src"
title = "My CMS Blog"

[output.html]
additional-css = ["custom.css"]
"#;
    fs::write(Path::new(BOOK_ROOT).join("book.toml"), config_content)?;

    // 8. 调用 mdBook 执行构建
    // mdbook 构建是同步阻塞的 CPU 密集型任务，放到 blocking 线程跑
    tokio::task::spawn_blocking(move || {
        let md = MDBook::load(BOOK_ROOT).expect("Failed to load mdbook");
        md.build().expect("Failed to build mdbook");
    })
    .await?;

    println!("✅ mdBook build finished successfully!");
    Ok(())
}
